apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialmedia-web
  template:
    metadata:
      labels:
        app: socialmedia-web
    spec:
      containers:
      - name: socialmedia-web
        image: erikmirkovic/socialmedia-web:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:3Vwh3KsM@postgres:5432/socialmedia"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_SECRET_KEY
        - name: DJANGO_DEBUG
          value: "True"
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.local"
        - name: DJANGO_ADMIN_URL
          value: "admin/"
        - name: DJANGO_ALLOWED_HOSTS
          value: "socialmedia.com,localhost,127.0.0.1,0.0.0.0"
        - name: DJANGO_ENV
          value: "development"
