apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/static"
