apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/media"
