apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: erikmirkovic/social-network-web:latest
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:8426@db:5432/socialmedia"
        - name: DJANGO_SECRET_KEY
          value: "YAUhXE0Xph6cyuLiN6gmneiXt6vn9aLCjFH5xwC8tYwGYlQZd8W4GNwJN2iFoCHE"
        - name: DJANGO_DEBUG
          value: "true"
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.local"
        - name: DJANGO_ENV
          value: "development"
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/staticfiles
          name: static-volume
        - mountPath: /app/media
          name: media-volume
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: pvc-static
      - name: media-volume
        persistentVolumeClaim:
          claimName: pvc-media
