apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: erikmirkovic/social-network-web:latest
        env:
        - name: DJANGO_SECRET_KEY
          value: "YAUhXE0Xph6cyuLiN6gmneiXt6vn9aLCjFH5xwC8tYwGYlQZd8W4GNwJN2iFoCHE"
        - name: DATABASE_URL
          value: "postgres://postgres:8426@db:5432/socialmedia"
        - name: DJANGO_DEBUG
          value: "True"
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.local"
        - name: DJANGO_ADMIN_URL
          value: "admin/"
        - name: DJANGO_ALLOWED_HOSTS
          value: "socialmedia.com,localhost,127.0.0.1"
        - name: DJANGO_ENV
          value: "development"
        - name: REDIS_URL
          value: "redis://redis:6379/1"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: media
          mountPath: /app/socialmedia/media
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-pv-claim
