# Generated by Django 4.2.13 on 2024-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_comment_text_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
