# Generated by Django 4.2.13 on 2024-07-15 21:28

from django.db import migrations, models
import socialmedia.social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_comment_text_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', validators=[socialmedia.social.models.validate_word_count]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='', validators=[socialmedia.social.models.validate_word_count]),
        ),
    ]
