# Generated by Django 4.2.13 on 2024-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_post_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
