# Generated by Django 4.2.13 on 2024-08-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_notification_trigger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow')], default='like', max_length=20),
        ),
    ]
